/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

import com.sun.javafx.font.FontFactory;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author lokesaheb
 */
public class GameHome extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form GameHome
     */
    static int topo=0;
    String turns;
    JButton jlc[][]=new JButton[3][3];
    
    public void refresh(){
        topo=0;
    for(int i=0;i<3;i++)
        {
            for(int j=0;j<3;j++) {
                jlc[i][j].setText("");
                
            }
        }
    lblstatus.setText("Player 1's turn");
    }
    public GameHome() {
        turns="player1";
        for(int i=0;i<3;i++)
        {
            for(int j=0;j<3;j++) {
                jlc[i][j]=new JButton("");
                jlc[i][j].setBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1));
                jlc[i][j].addActionListener(this);
            }
        }
        initComponents();
        lblstatus.setText("Player 1's turn");
        pnlscn.setBorder(BorderFactory.createLineBorder(Color.yellow, 5));
        
        for(int i=0;i<3;i++)
        {
            for(int j=0;j<3;j++) {
                pnlscn.add(jlc[i][j]);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlscn = new javax.swing.JPanel();
        lblstatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        pnlscn.setLayout(new java.awt.GridLayout(3, 3, 2, 2));

        lblstatus.setBackground(new java.awt.Color(229, 234, 22));
        lblstatus.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(pnlscn, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lblstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblstatus, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnlscn, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblstatus;
    private javax.swing.JPanel pnlscn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        JButton ato=(JButton)e.getSource();
        if(ato.getText().equals("")){
            if(turns.equals("player1")){
                ato.setForeground(Color.GREEN);
                ato.setFont(new java.awt.Font("Arial",1,24));
                ato.setText("X");
                turns="player2";
                System.out.println("Player 1 played");
                lblstatus.setText("Player 2's Turn");
                topo=topo+1;
            }
            else if(turns.equals("player2")) {
                ato.setForeground(Color.RED);
                ato.setFont(new java.awt.Font("Arial",1,24));
                ato.setText("O");
                turns="player1";
                System.out.println("Player 2 played");
                lblstatus.setText("Player 1's Turn");
                topo=topo+1;
            }
            
        }
        
        if(topo==9){
        JOptionPane.showMessageDialog(null,"Match Drawed");
        refresh();
        return;
        }
        
        if(jlc[0][0].getText().equals("X") && jlc[0][1].getText().equals("X") && jlc[0][2].getText().equals("X"))
        {
        JOptionPane.showMessageDialog(null,"Player 1 Wins");
        refresh();
        }
        else if(jlc[0][0].getText().equals("O") && jlc[0][1].getText().equals("O") && jlc[0][2].getText().equals("O"))
        {
        JOptionPane.showMessageDialog(null,"Player 2 Wins");
        refresh();
        }
        //Horizontal Row 1 
        
        if(jlc[1][0].getText().equals("X") && jlc[1][1].getText().equals("X") && jlc[1][2].getText().equals("X"))
        {
        JOptionPane.showMessageDialog(null,"Player 1 Wins");
        refresh();
        }
        else if(jlc[1][0].getText().equals("O") && jlc[1][1].getText().equals("O") && jlc[1][2].getText().equals("O"))
        {
        JOptionPane.showMessageDialog(null,"Player 2 Wins");
        refresh();
        }
        //Horizontal Row 2
        
        if(jlc[2][0].getText().equals("X") && jlc[2][1].getText().equals("X") && jlc[2][2].getText().equals("X"))
        {
        JOptionPane.showMessageDialog(null,"Player 1 Wins");
        refresh();
        }
        else if(jlc[2][0].getText().equals("O") && jlc[2][1].getText().equals("O") && jlc[2][2].getText().equals("O"))
        {
        JOptionPane.showMessageDialog(null,"Player 2 Wins");
        refresh();
        }
        //Horizontal Row 3
        
        
        
        else if(jlc[0][0].getText().equals("X") && jlc[1][0].getText().equals("X") && jlc[2][0].getText().equals("X"))
        {
        JOptionPane.showMessageDialog(null,"Player 1 Wins");
        refresh();
        }
        else if(jlc[0][0].getText().equals("O") && jlc[1][0].getText().equals("O") && jlc[2][0].getText().equals("O"))
        {
        JOptionPane.showMessageDialog(null,"Player 2 Wins");
        refresh();
        }
        //Vertical Column 1
        
        else if(jlc[0][1].getText().equals("X") && jlc[1][1].getText().equals("X") && jlc[2][1].getText().equals("X"))
        {
        JOptionPane.showMessageDialog(null,"Player 1 Wins");
        refresh();
        }
        else if(jlc[0][1].getText().equals("O") && jlc[1][1].getText().equals("O") && jlc[2][1].getText().equals("O"))
        {
        JOptionPane.showMessageDialog(null,"Player 2 Wins");
        refresh();
        }
        //Vertical Column 2
        
        
        else if(jlc[0][2].getText().equals("X") && jlc[1][2].getText().equals("X") && jlc[2][2].getText().equals("X"))
        {
        JOptionPane.showMessageDialog(null,"Player 1 Wins");
        refresh();
        }
        else if(jlc[0][2].getText().equals("O") && jlc[1][2].getText().equals("O") && jlc[2][2].getText().equals("O"))
        {
        JOptionPane.showMessageDialog(null,"Player 2 Wins");
        refresh();
        }
        //Vertical Column 3
        
        
        
        else if(jlc[0][0].getText().equals("X") && jlc[1][1].getText().equals("X") && jlc[2][2].getText().equals("X"))
        {
        JOptionPane.showMessageDialog(null,"Player 1 Wins");
        refresh();
        }
        else if(jlc[0][0].getText().equals("O") && jlc[1][1].getText().equals("O") && jlc[2][2].getText().equals("O"))
        {
        JOptionPane.showMessageDialog(null,"Player 2 Wins");
        refresh();
        }
        //Diagonal 1
        
        
        else if(jlc[2][0].getText().equals("X") && jlc[1][1].getText().equals("X") && jlc[0][2].getText().equals("X"))
        {
        JOptionPane.showMessageDialog(null,"Player 1 Wins");
        refresh();
        }
        else if(jlc[2][0].getText().equals("O") && jlc[1][1].getText().equals("O") && jlc[0][2].getText().equals("O"))
        {
        JOptionPane.showMessageDialog(null,"Player 2 Wins");
        refresh();
        }
        //Diagonal 2
        
        
         
        
    }
    
    
}

